branch-defaults:
  develop:
    environment: dev-letrus
  master:
      environment: prod-letrus
environment-defaults:
  dev-letrus:
    branch: null
    repository: null
global:
  application_name: dev-letrus
  default_ec2_keyname: Linux_virginia
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/Python 3.6 running
    on 64bit Amazon Linux/2.6.4
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: letrus-app-eb
  sc: git
  workspace_type: Application
